feat: added doc for sole traders
Goji-P2P/slate pull request #84
Opened 2021-02-12 13:33 UTC by stustill

Added sole trader support

2021-02-12 13:43 UTC, deanrecord approved these changes

2021-02-15 15:39 UTC, badgerwithagun commented on source/includes/platform-payments.md.erb
> +    "associatedIndivduals": [
typo?

2021-02-15 15:39 UTC, badgerwithagun commented on source/includes/platform-payments.md.erb
> +    "associatedIndivduals": [
typo?

2021-02-15 15:41 UTC, badgerwithagun commented on source/includes/platform-payments.md.erb
> +| ukCompany.associatedIndividuals  | array  | List of associated individuals.                                        |
Worth referencing the full breakdown of this array given above?

2021-02-15 15:42 UTC, badgerwithagun requested changes
A couple of tiny editorial tweaks but nothing major.

2021-02-15 15:48 UTC, merged